name: terraform-pr

on:
  pull_request:
    paths:
      - '**.tf'
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  TERRAFORM_SSH_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
  TF_VAR_pgp_pub_key: ${{ secrets.PGP_SIGNING_KEY }}
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: Run Checkov action
        id: checkov
        uses: bridgecrewio/checkov-action@master
      # - name: Setup OPA
      #   uses: open-policy-agent/setup-opa@v1
      #   with:
      #     version: latest
      # - name: Run OPA Tests 
      #   run: opa test policy/*.rego -v
  infracost:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.TERRAFORM_ROLE_ARN}}
          aws-region: eu-west-1
          role-duration-seconds: 3600
      - name: Setup Infracost
        uses: infracost/actions/setup@v1
        with:
          api-key: ${{ secrets.INFRACOST_API_TOKEN }}
          GIT_SSH_KEY: ${{ secrets.DEPLOY_SSH_PRIVATE_KEY }}
      - name: Generate plan
        id: terraform_plan
        uses: dflook/terraform-plan@v1
        with:
          path: ./
      - name: Generate Infracost JSON
        run: |
          cat ${{ steps.terraform_plan.outputs.json_plan_path }} > plan.json
          infracost breakdown --path plan.json --format json --out-file /tmp/infracost.json
        working-directory: ${{ env.working-directory }}
      - name: Post Infracost comment
        run: |
          infracost comment github --path /tmp/infracost.json \
            --repo $GITHUB_REPOSITORY \
            --github-token ${{github.token}} \
            --pull-request ${{github.event.pull_request.number}} \
            --behavior update
  plan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}
      - name: terraform fmt
        uses: dflook/terraform-fmt-check@v1
        with:
          path: ./
      - name: Commit Terraform
        uses: stefanzweifel/git-auto-commit-action@v4
        with: 
          commit_message: "Terraform formatting"
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.TERRAFORM_ROLE_ARN}}
          aws-region: eu-west-1
          role-duration-seconds: 3600
      - name: terraform plan
        id: terraform_plan
        uses: dflook/terraform-plan@v1
        with:
          path: ./
